[libdefaults]
 default_realm = ROOT.LOCAL
 dns_lookup_realm = true
 dns_lookup_kdc = true
 rdns = false

[domain_realm]
 .root.local = ROOT.LOCAL
 root.local = ROOT.LOCAL
 .dvuadmin.net = DVUADMIN.NET
 dvuadmin.net = DVUADMIN.NET
