[libdefaults]
  default_realm = ROOT.LOCAL
  dns_lookup_realm = true
  dns_lookup_kdc = true
  rdns = false
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true

[realms]
  ROOT.LOCAL = {
    kdc = cgw-ad2d00ap01.root.local
    kdc = cgw-ad2d00ap02.root.local
    admin_server = cgw-ad2d00ap01.root.local
    default_domain = root.local
  }

  DVUADMIN.NET = {
    kdc = caw-ad1p00ap04.dvuadmin.net
    kdc = skw-ad1p09ap01.dvuadmin.net
    kdc = caw-ad1p00ap02.dvuadmin.net
    admin_server = caw-ad1p00ap04.dvuadmin.net
    default_domain = dvuadmin.net
  }

[domain_realm]
  .root.local = ROOT.LOCAL
  root.local = ROOT.LOCAL
  .dvuadmin.net = DVUADMIN.NET
  dvuadmin.net = DVUADMIN.NET
