[libdefaults]
 default_realm = ROOT.LOCAL
 dns_lookup_realm = true
 dns_lookup_kdc = true
 rdns = false
 ticket_lifetime = 24h
 forwardable = true

[realms]
 ROOT.LOCAL = {
  kdc = dc1.root.local
  kdc = dc2.root.local
 }

 DVUADMIN.NET = {
  kdc = dc1.dvuadmin.net
  kdc = dc2.dvuadmin.net
 }

[domain_realm]
 .root.local = ROOT.LOCAL
 root.local = ROOT.LOCAL
 .dvuadmin.net = DVUADMIN.NET
 dvuadmin.net = DVUADMIN.NET
